In [1]:
import pandas as pd
import numpy as np

In [2]:
ratings = pd.read_csv('../data/ml-32m/ratings.csv')

In [3]:
print(f"Dataset Size: {ratings.memory_usage(index=True).sum() / 1024**2} MB")

Dataset Size: 976.5688514709473 MB

In [4]:
ratings.dtypes

userId         int64
movieId        int64
rating       float64
timestamp      int64
dtype: object

In [5]:
ratings.userId.max()

np.int64(200948)

In [6]:
# Set userId to be uint32 to save memory
ratings['userId'] = ratings['userId'].astype(np.uint32)

Ratings

In [7]:
ratings.rating.min()

np.float64(0.5)

In [8]:
ratings.rating.max()

np.float64(5.0)

In [9]:
# Set rating to be half since it can only take values from 0.5 to 5.0 in 0.5 increments
ratings['rating'] = ratings['rating'].astype(np.float16)

MovieId

In [10]:
print(ratings.movieId.max())

292757

In [11]:
# Set movieId to be uint32 to save memory
ratings['movieId'] = ratings['movieId'].astype(np.uint32)

Timestamp

In [12]:
print(ratings.timestamp.max())

1697164147

In [13]:
# Set timestamp to be uint32 to save memory
ratings['timestamp'] = ratings['timestamp'].astype(np.uint32)

### Size after setting correct dtypes

In [14]:
print(f"Dataset Size: {ratings.memory_usage(index=True).sum() / 1024**2} MB")

Dataset Size: 427.2489433288574 MB

# Make Implicit User-Item Matrix

Create a `scipy` sparse matrix to save spaces.
- Using Pandas `pivot` requires ~32GB of RAM
- `scipy` saves only the nonzero entries
- Matrix can be saved as `.npz` file

<font color="red"> Unused for now </font> because dataset is explicit feedback and that is the first test.

In [15]:
from scipy.sparse import csr_matrix

# Map userId and movieId to contiguous 0-based indices
user_ids = ratings['userId'].unique()
movie_ids = ratings['movieId'].unique()

user_to_idx = {uid: idx for idx, uid in enumerate(user_ids)}
movie_to_idx = {mid: idx for idx, mid in enumerate(movie_ids)}

row = ratings['userId'].map(user_to_idx).values
col = ratings['movieId'].map(movie_to_idx).values
data = np.ones(len(ratings), dtype=np.int8)  # implicit feedback: 1 = rated

user_item_matrix = csr_matrix((data, (row, col)), shape=(len(user_ids), len(movie_ids)))

print(f"Shape: {user_item_matrix.shape}")
print(f"Non-zero entries: {user_item_matrix.nnz:,}")
print(f"Sparsity: {1 - user_item_matrix.nnz / (user_item_matrix.shape[0] * user_item_matrix.shape[1]):.6f}")
print(f"Memory usage: {(user_item_matrix.data.nbytes + user_item_matrix.indices.nbytes + user_item_matrix.indptr.nbytes) / 1024**2:.2f} MB")

Shape: (200948, 84432)
Non-zero entries: 32,000,204
Sparsity: 0.998114
Memory usage: 153.36 MB

Save matrix

In [17]:
from scipy.sparse import save_npz
save_npz('../data/ml-32m/implicit_binary_user_item_matrix.npz', user_item_matrix)

# Make Explicit User-Item Matrix

In [17]:
from scipy.sparse import csr_matrix
from scipy.sparse import save_npz

user_ids = ratings['userId'].unique()
movie_ids = ratings['movieId'].unique()

user_to_idx = {uid: idx for idx, uid in enumerate(user_ids)}
movie_to_idx = {mid: idx for idx, mid in enumerate(movie_ids)}

row = ratings['userId'].map(user_to_idx).values
col = ratings['movieId'].map(movie_to_idx).values

data = ratings['rating'].values.astype(np.float32)  # use actual ratings
user_item_matrix = csr_matrix((data, (row, col)), shape=(len(user_ids), len(movie_ids)))
print(f"Shape: {user_item_matrix.shape}")
print(f"Non-zero entries: {user_item_matrix.nnz:,}")
print(f"Sparsity: {1 - user_item_matrix.nnz / (user_item_matrix.shape[0] * user_item_matrix.shape[1]):.6f}")
print(f"Memory usage: {(user_item_matrix.data.nbytes + user_item_matrix.indices.nbytes + user_item_matrix.indptr.nbytes) / 1024**2:.2f} MB")

save_npz('../data/ml-32m/explicit_user_item_matrix.npz', user_item_matrix)

Shape: (200948, 84432)
Non-zero entries: 32,000,204
Sparsity: 0.998114
Memory usage: 244.91 MB

But that's just the full matrix. We need train and test sets.

## Training Set
- For each user, leave their last interaction out of the train set to be used in test set

In [18]:
def pop_last_user_review(ratings_df):
    # Sort by timestamp to ensure the last review is at the end
    ratings_df = ratings_df.sort_values(by='timestamp')
    
    # Get the last review for each user
    last_reviews = ratings_df.groupby('userId').tail(1)
    
    # Remove the last reviews from the original DataFrame
    ratings_without_last = ratings_df[~ratings_df.index.isin(last_reviews.index)]
    
    return ratings_without_last, last_reviews

In [19]:
for user_id, group in ratings.groupby('userId'):
    print(f"User {user_id} has {len(group)} reviews")
ratings_without_last, last_reviews = pop_last_user_review(ratings)
print(f"Ratings without last review: {ratings_without_last.shape[0]}")
print(f"Last reviews: {last_reviews.shape[0]}")
ratings_without_last.to_csv('../data/ml-32m/ratings_without_last.csv', index=False)

User 1 has 141 reviews
User 2 has 52 reviews
User 3 has 147 reviews
User 4 has 27 reviews
User 5 has 33 reviews
User 6 has 26 reviews
User 7 has 44 reviews
User 8 has 31 reviews
User 9 has 58 reviews
User 10 has 660 reviews
User 11 has 20 reviews
User 12 has 23 reviews
User 13 has 65 reviews
User 14 has 29 reviews
User 15 has 82 reviews
User 16 has 295 reviews
User 17 has 86 reviews
User 18 has 138 reviews
User 19 has 47 reviews
User 20 has 140 reviews
User 21 has 35 reviews
User 22 has 63 reviews
User 23 has 63 reviews
User 24 has 45 reviews
User 25 has 87 reviews
User 26 has 33 reviews
User 27 has 62 reviews
User 28 has 2842 reviews
User 29 has 151 reviews
User 30 has 21 reviews
User 31 has 67 reviews
User 32 has 44 reviews
User 33 has 265 reviews
User 34 has 123 reviews
User 35 has 503 reviews
User 36 has 125 reviews
User 37 has 235 reviews
User 38 has 29 reviews
User 39 has 57 reviews
User 40 has 101 reviews
User 41 has 37 reviews
User 42 has 48 reviews
User 43 has 150 reviews
User 44 has 102 reviews
User 45 has 25 reviews
User 46 has 151 reviews
User 47 has 58 reviews
User 48 has 106 reviews
User 49 has 37 reviews
User 50 has 118 reviews
User 51 has 48 reviews
User 52 has 80 reviews
User 53 has 40 reviews
User 54 has 45 reviews
User 55 has 21 reviews
User 56 has 97 reviews
User 57 has 40 reviews
User 58 has 35 reviews
User 59 has 417 reviews
User 60 has 43 reviews
User 61 has 52 reviews
User 62 has 178 reviews
User 63 has 95 reviews
User 64 has 243 reviews
User 65 has 552 reviews
User 66 has 165 reviews
User 67 has 149 reviews
User 68 has 110 reviews
User 69 has 43 reviews
User 70 has 662 reviews
User 71 has 29 reviews
User 72 has 84 reviews
User 73 has 58 reviews
User 74 has 175 reviews
User 75 has 62 reviews
User 76 has 459 reviews
User 77 has 67 reviews
User 78 has 274 reviews
User 79 has 50 reviews
User 80 has 343 reviews
User 81 has 100 reviews
User 82 has 28 reviews
User 83 has 150 reviews
User 84 has 289 reviews
User 85 has 107 reviews
User 86 has 258 reviews
User 87 has 395 reviews
User 88 has 231 reviews
User 89 has 61 reviews
User 90 has 75 reviews
User 91 has 83 reviews
User 92 has 74 reviews
User 93 has 175 reviews
User 94 has 246 reviews
User 95 has 39 reviews
User 96 has 120 reviews
User 97 has 47 reviews
User 98 has 29 reviews
User 99 has 25 reviews
User 100 has 249 reviews
User 101 has 93 reviews
User 102 has 47 reviews
User 103 has 232 reviews
User 104 has 48 reviews
User 105 has 46 reviews
User 106 has 111 reviews
User 107 has 225 reviews
User 108 has 30 reviews
User 109 has 721 reviews
User 110 has 101 reviews
User 111 has 138 reviews
User 112 has 24 reviews
User 113 has 29 reviews
User 114 has 144 reviews
User 115 has 483 reviews
User 116 has 78 reviews
User 117 has 58 reviews
User 118 has 184 reviews
User 119 has 83 reviews
User 120 has 325 reviews
User 121 has 77 reviews
User 122 has 154 reviews
User 123 has 20 reviews
User 124 has 122 reviews
User 125 has 33 reviews
User 126 has 74 reviews
User 127 has 226 reviews
User 128 has 515 reviews
User 129 has 28 reviews
User 130 has 147 reviews
User 131 has 135 reviews
User 132 has 21 reviews
User 133 has 36 reviews
User 134 has 51 reviews
User 135 has 128 reviews
User 136 has 52 reviews
User 137 has 179 reviews
User 138 has 438 reviews
User 139 has 57 reviews
User 140 has 82 reviews
User 141 has 159 reviews
User 142 has 26 reviews
User 143 has 66 reviews
User 144 has 139 reviews
User 145 has 42 reviews
User 146 has 112 reviews
User 147 has 34 reviews
User 148 has 328 reviews
User 149 has 67 reviews
User 150 has 99 reviews
User 151 has 500 reviews
User 152 has 24 reviews
User 153 has 29 reviews
User 154 has 57 reviews
User 155 has 63 reviews
User 156 has 29 reviews
User 157 has 417 reviews
User 158 has 571 reviews
User 159 has 77 reviews
User 160 has 39 reviews
User 161 has 99 reviews
User 162 has 25 reviews
User 163 has 379 reviews
User 164 has 74 reviews
User 165 has 20 reviews
User 166 has 71 reviews
User 167 has 31 reviews
User 168 has 42 reviews
User 169 has 20 reviews
User 170 has 25 reviews
User 171 has 42 reviews
User 172 has 165 reviews
User 173 has 185 reviews
User 174 has 254 reviews
User 175 has 73 reviews
User 176 has 258 reviews
User 177 has 85 reviews
User 178 has 100 reviews
User 179 has 74 reviews
User 180 has 23 reviews
User 181 has 21 reviews
User 182 has 37 reviews
User 183 has 72 reviews
User 184 has 105 reviews
User 185 has 83 reviews
User 186 has 101 reviews
User 187 has 675 reviews
User 188 has 2202 reviews
User 189 has 73 reviews
User 190 has 55 reviews
User 191 has 27 reviews
User 192 has 49 reviews
User 193 has 27 reviews
User 194 has 132 reviews
User 195 has 47 reviews
User 196 has 95 reviews
User 197 has 192 reviews
User 198 has 165 reviews
User 199 has 29 reviews
User 200 has 40 reviews
User 201 has 89 reviews
User 202 has 54 reviews
User 203 has 339 reviews
User 204 has 285 reviews
User 205 has 39 reviews
User 206 has 143 reviews
User 207 has 89 reviews
User 208 has 540 reviews
User 209 has 107 reviews
User 210 has 75 reviews
User 211 has 97 reviews
User 212 has 203 reviews
User 213 has 212 reviews
User 214 has 81 reviews
User 215 has 222 reviews
User 216 has 67 reviews
User 217 has 22 reviews
User 218 has 132 reviews
User 219 has 82 reviews
User 220 has 129 reviews
User 221 has 21 reviews
User 222 has 25 reviews
User 223 has 210 reviews
User 224 has 101 reviews
User 225 has 36 reviews
User 226 has 273 reviews
User 227 has 30 reviews
User 228 has 850 reviews
User 229 has 41 reviews
User 230 has 35 reviews
User 231 has 36 reviews
User 232 has 147 reviews
User 233 has 27 reviews
User 234 has 35 reviews
User 235 has 63 reviews
User 236 has 24 reviews
User 237 has 255 reviews
User 238 has 467 reviews
User 239 has 596 reviews
User 240 has 630 reviews
User 241 has 72 reviews
User 242 has 485 reviews
User 243 has 41 reviews
User 244 has 87 reviews
User 245 has 595 reviews
User 246 has 42 reviews
User 247 has 41 reviews
User 248 has 87 reviews
User 249 has 41 reviews
User 250 has 74 reviews
User 251 has 52 reviews
User 252 has 136 reviews
User 253 has 53 reviews
User 254 has 108 reviews
User 255 has 74 reviews
User 256 has 38 reviews
User 257 has 30 reviews
User 258 has 209 reviews
User 259 has 59 reviews
User 260 has 178 reviews
User 261 has 78 reviews
User 262 has 36 reviews
User 263 has 57 reviews
User 264 has 32 reviews
User 265 has 2436 reviews
User 266 has 23 reviews
User 267 has 48 reviews
User 268 has 853 reviews
User 269 has 49 reviews
User 270 has 83 reviews
User 271 has 105 reviews
User 272 has 125 reviews
User 273 has 125 reviews
User 274 has 95 reviews
User 275 has 25 reviews
User 276 has 28 reviews
User 277 has 139 reviews
User 278 has 196 reviews
User 279 has 52 reviews
User 280 has 116 reviews
User 281 has 30 reviews
User 282 has 116 reviews
User 283 has 525 reviews
User 284 has 28 reviews
User 285 has 61 reviews
User 286 has 49 reviews
User 287 has 331 reviews
User 288 has 22 reviews
User 289 has 53 reviews
User 290 has 76 reviews
User 291 has 103 reviews
User 292 has 96 reviews
User 293 has 356 reviews
User 294 has 49 reviews
User 295 has 35 reviews
User 296 has 88 reviews
User 297 has 20 reviews
User 298 has 153 reviews
User 299 has 333 reviews
User 300 has 67 reviews
User 301 has 58 reviews
User 302 has 79 reviews
User 303 has 292 reviews
User 304 has 191 reviews
User 305 has 62 reviews
User 306 has 25 reviews
User 307 has 49 reviews
User 308 has 34 reviews
User 309 has 23 reviews
User 310 has 21 reviews
User 311 has 607 reviews
User 312 has 102 reviews
User 313 has 88 reviews
User 314 has 20 reviews
User 315 has 38 reviews
User 316 has 113 reviews
User 317 has 81 reviews
User 318 has 85 reviews
User 319 has 49 reviews
User 320 has 670 reviews
User 321 has 41 reviews
User 322 has 73 reviews
User 323 has 155 reviews
User 324 has 108 reviews
User 325 has 189 reviews
User 326 has 599 reviews
User 327 has 96 reviews
User 328 has 931 reviews
User 329 has 41 reviews
User 330 has 37 reviews
User 331 has 47 reviews
User 332 has 119 reviews
User 333 has 223 reviews
User 334 has 23 reviews
User 335 has 206 reviews
User 336 has 374 reviews
User 337 has 908 reviews
User 338 has 517 reviews
User 339 has 30 reviews
User 340 has 141 reviews
User 341 has 621 reviews
User 342 has 128 reviews
User 343 has 32 reviews
User 344 has 565 reviews
User 345 has 97 reviews
User 346 has 322 reviews
User 347 has 273 reviews
User 348 has 440 reviews
User 349 has 74 reviews
User 350 has 30 reviews
User 351 has 100 reviews
User 352 has 75 reviews
User 353 has 69 reviews
User 354 has 1262 reviews
User 355 has 389 reviews
User 356 has 53 reviews
User 357 has 20 reviews
User 358 has 222 reviews
User 359 has 59 reviews
User 360 has 1086 reviews
User 361 has 53 reviews
User 362 has 46 reviews
User 363 has 20 reviews
User 364 has 76 reviews
User 365 has 245 reviews
User 366 has 20 reviews
User 367 has 128 reviews
User 368 has 828 reviews
User 369 has 68 reviews
User 370 has 48 reviews
User 371 has 25 reviews
User 372 has 202 reviews
User 373 has 83 reviews
User 374 has 49 reviews
User 375 has 26 reviews
User 376 has 28 reviews
User 377 has 90 reviews
User 378 has 522 reviews
User 379 has 242 reviews
User 380 has 115 reviews
User 381 has 23 reviews
User 382 has 38 reviews
User 383 has 37 reviews
User 384 has 21 reviews
User 385 has 27 reviews
User 386 has 62 reviews
User 387 has 297 reviews
User 388 has 56 reviews
User 389 has 120 reviews
User 390 has 448 reviews
User 391 has 195 reviews
User 392 has 135 reviews
User 393 has 56 reviews
User 394 has 37 reviews
User 395 has 529 reviews
User 396 has 163 reviews
User 397 has 92 reviews
User 398 has 497 reviews
User 399 has 60 reviews
User 400 has 101 reviews
User 401 has 205 reviews
User 402 has 108 reviews
User 403 has 79 reviews
User 404 has 84 reviews
User 405 has 59 reviews
User 406 has 21 reviews
User 407 has 205 reviews
User 408 has 70 reviews
User 409 has 24 reviews
User 410 has 298 reviews
User 411 has 145 reviews
User 412 has 27 reviews
User 413 has 33 reviews
User 414 has 78 reviews
User 415 has 30 reviews
User 416 has 29 reviews
User 417 has 300 reviews
User 418 has 27 reviews
User 419 has 76 reviews
User 420 has 167 reviews
User 421 has 165 reviews
User 422 has 51 reviews
User 423 has 118 reviews
User 424 has 643 reviews
User 425 has 155 reviews
User 426 has 31 reviews
User 427 has 27 reviews
User 428 has 56 reviews
User 429 has 22 reviews
User 430 has 920 reviews
User 431 has 337 reviews
User 432 has 104 reviews
User 433 has 186 reviews
User 434 has 24 reviews
User 435 has 75 reviews
User 436 has 64 reviews
User 437 has 563 reviews
User 438 has 314 reviews
User 439 has 50 reviews
User 440 has 38 reviews
User 441 has 149 reviews
User 442 has 75 reviews
User 443 has 45 reviews
User 444 has 24 reviews
User 445 has 24 reviews
User 446 has 55 reviews
User 447 has 1096 reviews
User 448 has 92 reviews
User 449 has 103 reviews
User 450 has 125 reviews
User 451 has 77 reviews
User 452 has 34 reviews
User 453 has 111 reviews
User 454 has 165 reviews
User 455 has 37 reviews
User 456 has 81 reviews
User 457 has 288 reviews
User 458 has 73 reviews
User 459 has 190 reviews
User 460 has 217 reviews
User 461 has 48 reviews
User 462 has 28 reviews
User 463 has 23 reviews
User 464 has 20 reviews
User 465 has 29 reviews
User 466 has 214 reviews
User 467 has 37 reviews
User 468 has 262 reviews
User 469 has 50 reviews
User 470 has 41 reviews
User 471 has 22 reviews
User 472 has 186 reviews
User 473 has 137 reviews
User 474 has 37 reviews
User 475 has 104 reviews
User 476 has 51 reviews
User 477 has 37 reviews
User 478 has 891 reviews
User 479 has 397 reviews
User 480 has 116 reviews
User 481 has 409 reviews
User 482 has 109 reviews
User 483 has 321 reviews
User 484 has 42 reviews
User 485 has 54 reviews
User 486 has 126 reviews
User 487 has 51 reviews
User 488 has 56 reviews
User 489 has 145 reviews
User 490 has 91 reviews
User 491 has 46 reviews
User 492 has 20 reviews
User 493 has 28 reviews
User 494 has 28 reviews
User 495 has 232 reviews
User 496 has 30 reviews
User 497 has 30 reviews
User 498 has 173 reviews
User 499 has 23 reviews
User 500 has 62 reviews
User 501 has 35 reviews
User 502 has 41 reviews
User 503 has 340 reviews
User 504 has 495 reviews
User 505 has 115 reviews
User 506 has 39 reviews
User 507 has 23 reviews
User 508 has 127 reviews
User 509 has 64 reviews
User 510 has 40 reviews
User 511 has 399 reviews
User 512 has 35 reviews
User 513 has 64 reviews
User 514 has 111 reviews
User 515 has 25 reviews
User 516 has 162 reviews
User 517 has 37 reviews
User 518 has 24 reviews
User 519 has 32 reviews
User 520 has 128 reviews
User 521 has 119 reviews
User 522 has 53 reviews
User 523 has 20 reviews
User 524 has 41 reviews
User 525 has 244 reviews
User 526 has 57 reviews
User 527 has 1313 reviews
User 528 has 25 reviews
User 529 has 36 reviews
User 530 has 801 reviews
User 531 has 78 reviews
User 532 has 103 reviews
User 533 has 412 reviews
User 534 has 30 reviews
User 535 has 156 reviews
User 536 has 243 reviews
User 537 has 195 reviews
User 538 has 201 reviews
User 539 has 136 reviews
User 540 has 97 reviews
User 541 has 96 reviews
User 542 has 375 reviews
User 543 has 22 reviews
User 544 has 57 reviews
User 545 has 300 reviews
User 546 has 126 reviews
User 547 has 1030 reviews
User 548 has 50 reviews
User 549 has 83 reviews
User 550 has 357 reviews
User 551 has 809 reviews
User 552 has 24 reviews
User 553 has 51 reviews
User 554 has 20 reviews
User 555 has 36 reviews
User 556 has 373 reviews
User 557 has 143 reviews
User 558 has 36 reviews
User 559 has 35 reviews
User 560 has 413 reviews
User 561 has 62 reviews
User 562 has 52 reviews
User 563 has 39 reviews
User 564 has 287 reviews
User 565 has 586 reviews
User 566 has 29 reviews
User 567 has 301 reviews
User 568 has 190 reviews
User 569 has 164 reviews
User 570 has 21 reviews
User 571 has 78 reviews
User 572 has 102 reviews
User 573 has 28 reviews
User 574 has 164 reviews
User 575 has 45 reviews
User 576 has 36 reviews
User 577 has 121 reviews
User 578 has 54 reviews
User 579 has 39 reviews
User 580 has 144 reviews
User 581 has 31 reviews
User 582 has 69 reviews
User 583 has 184 reviews
User 584 has 21 reviews
User 585 has 31 reviews
User 586 has 35 reviews
User 587 has 710 reviews
User 588 has 1021 reviews
User 589 has 26 reviews
User 590 has 50 reviews
User 591 has 39 reviews
User 592 has 102 reviews
User 593 has 305 reviews
User 594 has 74 reviews
User 595 has 71 reviews
User 596 has 82 reviews
User 597 has 40 reviews
User 598 has 117 reviews
User 599 has 97 reviews
User 600 has 569 reviews
User 601 has 47 reviews
User 602 has 40 reviews
User 603 has 76 reviews
User 604 has 157 reviews
User 605 has 21 reviews
User 606 has 78 reviews
User 607 has 34 reviews
User 608 has 23 reviews
User 609 has 84 reviews
User 610 has 394 reviews
User 611 has 20 reviews
User 612 has 39 reviews
User 613 has 99 reviews
User 614 has 482 reviews
User 615 has 21 reviews
User 616 has 84 reviews
User 617 has 50 reviews
User 618 has 31 reviews
User 619 has 44 reviews
User 620 has 54 reviews
User 621 has 62 reviews
User 622 has 246 reviews
User 623 has 74 reviews
User 624 has 68 reviews
User 625 has 21 reviews
User 626 has 51 reviews
User 627 has 564 reviews
User 628 has 26 reviews
User 629 has 24 reviews
User 630 has 29 reviews
User 631 has 373 reviews
User 632 has 458 reviews
User 633 has 259 reviews
User 634 has 587 reviews
User 635 has 59 reviews
User 636 has 39 reviews
User 637 has 218 reviews
User 638 has 202 reviews
User 639 has 36 reviews
User 640 has 40 reviews
User 641 has 91 reviews
User 642 has 29 reviews
User 643 has 61 reviews
User 644 has 28 reviews
User 645 has 100 reviews
User 646 has 88 reviews
User 647 has 138 reviews
User 648 has 70 reviews
User 649 has 243 reviews
User 650 has 24 reviews
User 651 has 147 reviews
User 652 has 65 reviews
User 653 has 22 reviews
User 654 has 40 reviews
User 655 has 1376 reviews
User 656 has 101 reviews
User 657 has 48 reviews
User 658 has 175 reviews
User 659 has 30 reviews
User 660 has 57 reviews
User 661 has 1440 reviews
User 662 has 45 reviews
User 663 has 39 reviews
User 664 has 50 reviews
User 665 has 54 reviews
User 666 has 253 reviews
User 667 has 49 reviews
User 668 has 162 reviews
User 669 has 20 reviews
User 670 has 57 reviews
User 671 has 153 reviews
User 672 has 40 reviews
User 673 has 580 reviews
User 674 has 43 reviews
User 675 has 43 reviews
User 676 has 88 reviews
User 677 has 43 reviews
User 678 has 37 reviews
User 679 has 34 reviews
User 680 has 154 reviews
User 681 has 21 reviews
User 682 has 91 reviews
User 683 has 451 reviews
User 684 has 96 reviews
User 685 has 58 reviews
User 686 has 102 reviews
User 687 has 525 reviews
User 688 has 76 reviews
User 689 has 27 reviews
User 690 has 82 reviews
User 691 has 315 reviews
User 692 has 148 reviews
User 693 has 24 reviews
User 694 has 20 reviews
User 695 has 618 reviews
User 696 has 57 reviews
User 697 has 58 reviews
User 698 has 284 reviews
User 699 has 122 reviews
User 700 has 24 reviews
User 701 has 285 reviews
User 702 has 1113 reviews
User 703 has 61 reviews
User 704 has 225 reviews
User 705 has 155 reviews
User 706 has 58 reviews
User 707 has 470 reviews
User 708 has 100 reviews
User 709 has 164 reviews
User 710 has 35 reviews
User 711 has 708 reviews
User 712 has 199 reviews
User 713 has 205 reviews
User 714 has 75 reviews
User 715 has 38 reviews
User 716 has 110 reviews
User 717 has 184 reviews
User 718 has 21 reviews
User 719 has 41 reviews
User 720 has 24 reviews
User 721 has 231 reviews
User 722 has 430 reviews
User 723 has 99 reviews
User 724 has 209 reviews
User 725 has 225 reviews
User 726 has 76 reviews
User 727 has 20 reviews
User 728 has 35 reviews
User 729 has 62 reviews
User 730 has 30 reviews
User 731 has 29 reviews
User 732 has 27 reviews
User 733 has 329 reviews
User 734 has 21 reviews
User 735 has 53 reviews
User 736 has 139 reviews
User 737 has 480 reviews
User 738 has 126 reviews
User 739 has 33 reviews
User 740 has 100 reviews
User 741 has 80 reviews
User 742 has 35 reviews
User 743 has 173 reviews
User 744 has 147 reviews
User 745 has 451 reviews
User 746 has 143 reviews
User 747 has 20 reviews
User 748 has 129 reviews
User 749 has 145 reviews
User 750 has 230 reviews
User 751 has 53 reviews
User 752 has 21 reviews
User 753 has 28 reviews
User 754 has 68 reviews
User 755 has 23 reviews
User 756 has 61 reviews
User 757 has 460 reviews
User 758 has 29 reviews
User 759 has 71 reviews
User 760 has 20 reviews
User 761 has 23 reviews
User 762 has 214 reviews
User 763 has 165 reviews
User 764 has 70 reviews
User 765 has 80 reviews
User 766 has 95 reviews
User 767 has 27 reviews
User 768 has 120 reviews
User 769 has 56 reviews
User 770 has 82 reviews
User 771 has 29 reviews
User 772 has 21 reviews
User 773 has 39 reviews
User 774 has 29 reviews
User 775 has 72 reviews
User 776 has 94 reviews
User 777 has 36 reviews
User 778 has 292 reviews
User 779 has 81 reviews
User 780 has 116 reviews
User 781 has 86 reviews
User 782 has 24 reviews
User 783 has 21 reviews
User 784 has 439 reviews
User 785 has 141 reviews
User 786 has 38 reviews
User 787 has 22 reviews
User 788 has 21 reviews
User 789 has 21 reviews
User 790 has 29 reviews
User 791 has 53 reviews
User 792 has 30 reviews
User 793 has 22 reviews
User 794 has 34 reviews
User 795 has 31 reviews
User 796 has 100 reviews
User 797 has 23 reviews
User 798 has 666 reviews
User 799 has 20 reviews
User 800 has 25 reviews
User 801 has 28 reviews
User 802 has 96 reviews
User 803 has 393 reviews
User 804 has 45 reviews
User 805 has 68 reviews
User 806 has 21 reviews
User 807 has 120 reviews
User 808 has 20 reviews
User 809 has 22 reviews
User 810 has 828 reviews
User 811 has 140 reviews
User 812 has 26 reviews
User 813 has 41 reviews
User 814 has 49 reviews
User 815 has 481 reviews
User 816 has 118 reviews
User 817 has 54 reviews
User 818 has 21 reviews
User 819 has 24 reviews
User 820 has 105 reviews
User 821 has 79 reviews
User 822 has 68 reviews
User 823 has 26 reviews

## Test Set
- The left-one-out ratings
- Sample 100 random items that user hasn't interacted with for test set
- Set seed of 42

In [24]:
def sample_unrated_items_fast(user_item_sparse, user_ids, movie_ids, num_samples=100):
    rng = np.random.default_rng(42)
    num_users, num_items = user_item_sparse.shape
    rows, cols = [], []
    
    for u in range(num_users):
        start, end = user_item_sparse.indptr[u], user_item_sparse.indptr[u + 1]
        rated = user_item_sparse.indices[start:end]
        # Random sampling by rejection — fast when sparsity is high
        sampled = set()
        while len(sampled) < num_samples:
            candidates = rng.integers(0, num_items, size=num_samples * 2)
            for c in candidates:
                if c not in rated and c not in sampled:
                    sampled.add(c)
                    if len(sampled) == num_samples:
                        break
        rows.extend([user_ids[u]] * num_samples)
        cols.extend([movie_ids[s] for s in sampled])
    
    return pd.DataFrame({'userId': rows, 'movieId': cols})

Defined in cell 17

In [27]:
unrated_items = sample_unrated_items_fast(user_item_matrix, user_ids, movie_ids, num_samples=100)

In [28]:
unrated_items.head()

   userId  movieId
0       1   194212
1       1   100338
2       1   172433
3       1   181407
4       1    26197

### Concatenate with last interaction

In [31]:
last_reviews.head()

c:\Users\Atvar\miniconda3\envs\qc\Lib\site-packages\pandas\io\formats\format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

          userId  movieId  rating  timestamp
19851495  124331      109     1.0  825080160
6352965    39588      441     3.0  825638400
8114426    50823      446     5.0  825638400
5612144    35011      357     5.0  825638400
9415346    58832      509     5.0  825638400

In [32]:
unrated_items_with_labels = unrated_items.copy()
unrated_items_with_labels['label'] = 0  # unrated items get label 0

In [33]:
test_set = pd.concat([last_reviews[['userId', 'movieId', 'rating']].rename(columns={'rating': 'label'}), unrated_items_with_labels], ignore_index=True)

In [34]:
test_set.head()

   userId  movieId  label
0  124331      109    1.0
1   39588      441    3.0
2   50823      446    5.0
3   35011      357    5.0
4   58832      509    5.0

In [35]:
test_set.shape

(20295748, 3)

In [36]:
unrated_items.shape

(20094800, 2)

In [37]:
test_set.to_csv('../data/ml-32m/test_set.csv', index=False)